#include "div.h"			//d
#include "cos.h"			//d
#include "avg.h"			//d
#include "abs.h"			//d
#include "isequall.h"		//d
#include "mode.h"			//d
#include "transpose.h"		//d
#include "isprime.h"		//d
#include "count.h"			//d
#include "toupper.h"		//d
#include "countno.h"		//d
#include "isunique.h"		//d
#include "isort.h"			//d
#include "log.h"			//d
#include "is_mat_eq.h"		//d	